// Writes a small game the phone page's browser test can play against: four throwaway players,
// their words, who each one is hunting, and the bundle that holds it all. Nothing in it has any
// value; every secret is generated on the spot and discarded.
//
//   pnpm --filter @blindside/cli fixture:phone > app/e2e/fixtures/phone.json
// SPDX-License-Identifier: Apache-2.0

import {
  buildStartPlan,
  encodeBundle,
  joinCard,
  keysForGame,
  myAssignment,
  newIdentity,
  wordCodeText,
} from "@blindside/core";

const GAME = "phonefixture0001";
const NAMES = ["Asha", "Ben", "Cleo", "Dara"];

const seats = NAMES.map((name) => {
  const identity = newIdentity();
  return { name, identity, keys: keysForGame(identity.words, GAME) };
});
const plan = buildStartPlan(seats.map((seat) => joinCard(seat.identity, seat.keys, seat.name)));

const fixture = {
  note: "Generated by pnpm --filter @blindside/cli fixture:phone. Throwaway identities for a browser test.",
  game: GAME,
  bundle: encodeBundle({ game: GAME, items: plan.items }),
  players: seats.map((seat) => ({
    name: seat.name,
    words: wordCodeText(seat.identity.words),
    target: myAssignment(seat.keys, plan.items)?.targetName ?? null,
  })),
};

process.stdout.write(`${JSON.stringify(fixture, null, 2)}\n`);
